spring:
  application:
    name: microservice-provider-user
  datasource:
    url: jdbc:mysql://192.168.80.128:3306/springtest
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8001
mybatis:
  mapper-locations: classpath:/mapper/*.xml